// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Sumant Brass Industries",
  category: "Manufacturer",
  address: "\nPlot No.372/5, G.I.D.C. Phase 2, GIDC Phase-2, Dared, Jamnagar, Gujarat 361012",
  phone: "\n097376 54341",
  email: "",
  website: "http://www.sumantbrassindustries.com/",
  mapUrl: "https://www.google.com/maps/place/Sumant+Brass+Industries/@22.4134957,70.0538824,794m/data=!3m2!1e3!4b1!4m6!3m5!1s0x39576b1d8b19d217:0x2f68582554703bcb!8m2!3d22.4134957!4d70.0564573!16s%2Fg%2F11sfb7xxqr?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "22.4134957",
  longitude: "70.0538824",
  rating: "",
  reviewsCount: "3",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.png",
  images: ["/images/img_1783103200962_0.jpg", "/images/img_1783103202304_1.jpg", "/images/img_1783103202670_2.jpg", "/images/img_1783103203077_3.jpg", "/images/img_1783103203441_4.jpg", "/images/img_1783103203833_5.jpg", "/images/img_1783103204227_6.jpg", "/images/gmap_1783103205313_0.jpg", "/images/gmap_1783103205577_1.jpg", "/images/gmap_1783103205833_2.jpg", "/images/gmap_1783103206118_3.jpg", "/images/website_0.jpg", "/images/website_1.jpg", "/images/website_2.jpg", "/images/website_3.jpg", "/images/website_4.jpg", "/images/website_5.jpg", "/images/website_6.jpg", "http://www.sumantbrassindustries.com/images/1.jpg", "http://www.sumantbrassindustries.com/images/2.jpg", "http://www.sumantbrassindustries.com/images/3.jpg", "http://www.sumantbrassindustries.com/images/4.jpg", "http://www.sumantbrassindustries.com/images/5.jpg", "http://www.sumantbrassindustries.com/images/6.jpg", "http://www.sumantbrassindustries.com/images/7.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Jamnagar's Brass Experts",
  heroDescription: "Sumant Brass Industries is a leading manufacturer of brass products, located in the heart of Gujarat. With a strong presence in GIDC Phase 2, Jamnagar, we cater to a wide range of industries. Our products are known for their exceptional quality and durability.",
  aboutTitle: "Our Story So Far",
  aboutText: "Located at  Plot No.372/5, G.I.D.C. Phase 2, our state-of-the-art facility is equipped with the latest technology and machinery. We have been serving our customers with passion and dedication, providing them with top-notch brass products. Our team of experts ensures that every product that leaves our facility meets the highest standards of quality.",
  services: [
    { icon: "🔩", title: "Brass Fittings Manufacturing", description: "We specialize in creating high-quality brass fittings for various industries, including plumbing and sanitary" },
    { icon: "💡", title: "Lighting Fixture Manufacturing", description: "Our expertise in manufacturing brass lighting fixtures has earned us a reputation as a trusted supplier in the industry" },
    { icon: "🚿", title: "Valve Manufacturing", description: "We design and manufacture a wide range of brass valves for industrial applications, ensuring precision and reliability" },
    { icon: "🔧", title: "Brass Hardware Manufacturing", description: "From door handles to hinges, we create a variety of brass hardware products for construction and furniture industries" },
    { icon: "📦", title: "Customized Brass Products", description: "Our team works closely with clients to design and manufacture customized brass products that meet their specific requirements" },
    { icon: "🔨", title: "Brass CNC Machining", description: "We utilize advanced CNC machining technology to create intricate and complex brass parts with precision and accuracy" }
  ],
  whyChooseUs: [
    { icon: "🏭", title: "State-of-the-Art Infrastructure", description: "Our modern facility in GIDC Phase 2, Jamnagar, is equipped with the latest machinery and technology to ensure efficient production" },
    { icon: "📈", title: "Quality Focus", description: "We maintain the highest standards of quality, with a robust quality control process in place to ensure that every product meets our customers' expectations" },
    { icon: "👥", title: "Experienced Team", description: "Our team of skilled professionals has years of experience in the brass manufacturing industry, enabling us to provide expert solutions to our customers" },
    { icon: "📦", title: "Timely Delivery", description: "We prioritize timely delivery, ensuring that our customers receive their orders on schedule, every time" }
  ],
  testimonials: [
    { name: "Mahesh Chauhan", role: "Google Review", text: "This Place is currently right", rating: 5 }
  ],
  faq: { items: [{ question: "What types of brass products do you manufacture?", answer: "We manufacture a wide range of brass products, including fittings, lighting fixtures, valves, hardware, and customized products." },
    { question: "What is your production capacity?", answer: "Our state-of-the-art facility in GIDC Phase 2, Jamnagar, has a production capacity of 10,000 units per month, which can be scaled up to meet customer demand." },
    { question: "Do you provide customization options?", answer: "Yes, we offer customization options for our brass products, working closely with clients to design and manufacture products that meet their specific requirements." },
    { question: "What is your quality control process?", answer: "We have a robust quality control process in place, which includes rigorous testing and inspection of every product before it is shipped to our customers." },
    { question: "What is your delivery timeline?", answer: "We prioritize timely delivery, ensuring that our customers receive their orders within 7-10 working days, depending on the location and quantity of the order." },
    { question: "Can I visit your facility?", answer: "Yes, we welcome customers to visit our facility in GIDC Phase 2, Jamnagar, to see our production capabilities and meet our team." }] },
  ctaTitle: "Get a Quote Today",
  ctaDescription: "Contact us to discuss your brass product requirements and receive a competitive quote.",
  ctaButtonText: "Request Quote",
  metaDescription: "Sumant Brass Industries: Manufacturer of high-quality brass products in Jamnagar, Gujarat.",
};

export const siteConfig = {
  layout: "playful",
  theme: "elegant",
  sections: ["gallery", "services", "about", "testimonials", "faq", "contact"],
  heroVariant: "fullscreen-image",
  navStyle: "minimal-top-nav",
  animationStyle: "parallax-sections",
  cardStyle: "rounded-2xl shadow-sm border",
  darkMode: false,
};
