// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Sumant Brass Industries",
  category: "Manufacturer",
  address: "\nPlot No.372/5, G.I.D.C. Phase 2, GIDC Phase-2, Dared, Jamnagar, Gujarat 361012",
  phone: "\n097376 54341",
  email: "",
  website: "http://www.sumantbrassindustries.com/",
  mapUrl: "https://www.google.com/maps/place/Sumant+Brass+Industries/@22.4134957,70.0538824,794m/data=!3m2!1e3!4b1!4m6!3m5!1s0x39576b1d8b19d217:0x2f68582554703bcb!8m2!3d22.4134957!4d70.0564573!16s%2Fg%2F11sfb7xxqr?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "22.4134957",
  longitude: "70.0538824",
  rating: "",
  reviewsCount: "3",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.png",
  images: ["/images/img_1783102816518_0.jpg", "/images/img_1783102817746_1.jpg", "/images/img_1783102818091_2.jpg", "/images/img_1783102818444_3.jpg", "/images/img_1783102818799_4.jpg", "/images/img_1783102819140_5.jpg", "/images/img_1783102819473_6.jpg", "/images/gmap_1783102820543_0.jpg", "/images/gmap_1783102820848_1.jpg", "/images/gmap_1783102821077_2.jpg", "/images/gmap_1783102821381_3.jpg", "/images/website_0.jpg", "/images/website_1.jpg", "/images/website_2.jpg", "/images/website_3.jpg", "/images/website_4.jpg", "/images/website_5.jpg", "/images/website_6.jpg", "http://www.sumantbrassindustries.com/images/1.jpg", "http://www.sumantbrassindustries.com/images/2.jpg", "http://www.sumantbrassindustries.com/images/3.jpg", "http://www.sumantbrassindustries.com/images/4.jpg", "http://www.sumantbrassindustries.com/images/5.jpg", "http://www.sumantbrassindustries.com/images/6.jpg", "http://www.sumantbrassindustries.com/images/7.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Brass Experts of Jamnagar",
  heroDescription: "Located in the heart of Gujarat, Sumant Brass Industries is a leading manufacturer of brass products. With a strong presence in GIDC Phase 2, we cater to a wide range of industries. Our expertise in brass manufacturing has made us a trusted name in the region.",
  aboutTitle: "Our Journey in Brass Manufacturing",
  aboutText: "At Sumant Brass Industries, we take pride in our state-of-the-art facilities located at  Plot No.372/5, G.I.D.C. Phase 2, GIDC Phase-2, Dared, Jamnagar, Gujarat 361012. With a focus on quality and innovation, we have established ourselves as a reputable manufacturer of brass products. Our team of skilled professionals ensures that every product meets the highest standards of quality and reliability. We are committed to delivering exceptional service to our customers and building long-term relationships with them.",
  services: [
    { icon: "💡", title: "Brass Fittings Manufacturing", description: "We specialize in manufacturing high-quality brass fittings, including valves, pipes, and tubes." },
    { icon: "🔨", title: "Brass Component Production", description: "Our facility is equipped to produce a wide range of brass components, including bolts, nuts, and screws." },
    { icon: "📦", title: "Custom Brass Solutions", description: "We offer customized brass solutions to meet the specific needs of our clients, including precision engineering and machining." },
    { icon: "🚚", title: "Brass Product Export", description: "We export our brass products to various countries, ensuring timely delivery and competitive pricing." },
    { icon: "👥", title: "Brass Industry Consulting", description: "Our experienced team provides consulting services to businesses in the brass industry, helping them improve their operations and efficiency." },
    { icon: "💼", title: "Brass Product Development", description: "We work closely with our clients to develop new brass products, from concept to production, ensuring that they meet the required standards and specifications." }
  ],
  whyChooseUs: [
    { icon: "💯", title: "Quality Focus", description: "At Sumant Brass Industries, we are committed to delivering high-quality brass products that meet the required standards and specifications." },
    { icon: "📈", title: "Innovative Solutions", description: "Our team of experts is dedicated to providing innovative solutions to our clients, helping them stay ahead in the competitive market." },
    { icon: "👍", title: "Customer Centricity", description: "We prioritize our customers' needs, ensuring that we deliver exceptional service and support to build long-term relationships with them." },
    { icon: "🏭", title: "State-of-the-Art Facilities", description: "Our facility in GIDC Phase 2 is equipped with the latest technology and machinery, enabling us to produce high-quality brass products efficiently." }
  ],
  testimonials: [
    { name: "Mahesh Chauhan", role: "Google Review", text: "This Place is currently right", rating: 5 }
  ],
  faq: { items: [{ question: "What types of brass products do you manufacture?", answer: "At Sumant Brass Industries, we manufacture a wide range of brass products, including fittings, components, and custom solutions. Please contact us for more information on our product offerings." },
    { question: "Do you offer customized brass solutions?", answer: "Yes, we offer customized brass solutions to meet the specific needs of our clients. Our team of experts will work closely with you to develop a tailored solution that meets your requirements." },
    { question: "What is your quality control process?", answer: "We have a rigorous quality control process in place to ensure that all our brass products meet the required standards and specifications. Our team of quality control experts inspect every product before it is shipped to our clients." },
    { question: "Can I visit your facility in GIDC Phase 2?", answer: "Yes, you are welcome to visit our facility in GIDC Phase 2. Please contact us in advance to schedule a meeting and tour of our facility." },
    { question: "Do you export your brass products?", answer: "Yes, we export our brass products to various countries. We have a strong network of logistics partners to ensure timely and efficient delivery of our products." },
    { question: "How do I get a quote for your brass products?", answer: "Please contact us with your requirements, and we will provide you with a quote for our brass products. You can reach us via phone, email, or through our website." }] },
  ctaTitle: "Get in Touch with Us",
  ctaDescription: "Contact us today to learn more about our brass products and services. Our team of experts will be happy to assist you.",
  ctaButtonText: "Contact Now",
  metaDescription: "Sumant Brass Industries: Leading manufacturer of brass products in Jamnagar, Gujarat.",
};

export const siteConfig = {
  layout: "playful",
  theme: "elegant",
  sections: ["gallery", "more", "customer", "skip", "lang", "whatsapp", "aria", "hamburger/mobile", "subtle", "about", "structured", "testimonials", "image", "google", "critical:", "social", "alt", "open", "canonical", "a", "lazy", "faq", "contact"],
  heroVariant: "fullscreen-image",
  navStyle: "minimal-top-nav",
  animationStyle: "parallax-sections",
  cardStyle: "rounded-2xl shadow-sm border",
  darkMode: false,
};
