// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Sumant Brass Industries",
  category: "Manufacturer",
  address: "\nPlot No.372/5, G.I.D.C. Phase 2, GIDC Phase-2, Dared, Jamnagar, Gujarat 361012",
  phone: "\n097376 54341",
  email: "",
  website: "http://www.sumantbrassindustries.com/",
  mapUrl: "https://www.google.com/maps/place/Sumant+Brass+Industries/@22.4135728,70.0564298,56a,75y,159.53h,90t/data=!3m7!1e1!3m5!1sJ0Rlm68EpTEketLhtU4CVg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D0%26panoid%3DJ0Rlm68EpTEketLhtU4CVg%26yaw%3D159.53156!7i16384!8i8192!4m6!3m5!1s0x39576b1d8b19d217:0x2f68582554703bcb!8m2!3d22.4134957!4d70.0564573!16s%2Fg%2F11sfb7xxqr?entry=ttu&g_ep=EgoyMDI2MDcwNS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "22.4135728",
  longitude: "70.0564298",
  rating: "",
  reviewsCount: "3",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.png",
  images: ["/images/img_1783509968798_0.jpg", "/images/img_1783509970059_1.jpg", "/images/img_1783509970459_2.jpg", "/images/img_1783509970853_3.jpg", "/images/img_1783509971259_4.jpg", "/images/img_1783509971703_5.jpg", "/images/img_1783509972072_6.jpg", "/images/gmap_1783509973422_0.jpg", "/images/gmap_1783509974116_1.jpg", "/images/gmap_1783509974674_2.jpg", "/images/gmap_1783509975312_3.jpg", "/images/website_0.jpg", "/images/website_1.jpg", "/images/website_2.jpg", "/images/website_3.jpg", "/images/website_4.jpg", "/images/website_5.jpg", "/images/website_6.jpg", "http://www.sumantbrassindustries.com/images/1.jpg", "http://www.sumantbrassindustries.com/images/2.jpg", "http://www.sumantbrassindustries.com/images/3.jpg", "http://www.sumantbrassindustries.com/images/4.jpg", "http://www.sumantbrassindustries.com/images/5.jpg", "http://www.sumantbrassindustries.com/images/6.jpg", "http://www.sumantbrassindustries.com/images/7.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Jamnagar's Brass Experts",
  heroDescription: "Welcome to Sumant Brass Industries, a leading manufacturer of high-quality brass products in Gujarat. Located in the heart of Jamnagar, our state-of-the-art facilities enable us to deliver exceptional products. With a strong commitment to quality and customer satisfaction, we have established ourselves as a trusted name in the industry.",
  aboutTitle: "Our Story: Crafting Excellence",
  aboutText: "Sumant Brass Industries is situated at Plot No.372/5, G.I.D.C. Phase 2, in the bustling industrial hub of Jamnagar. Our strategic location allows us to cater to a diverse range of clients across the region. With a strong focus on innovation and quality, we have been consistently delivering outstanding brass products that meet the highest standards of excellence. Our team of skilled professionals is dedicated to ensuring that every product that leaves our facility meets the highest standards of quality and craftsmanship.",
  services: [
    { icon: "🏭", title: "Brass Component Manufacturing", description: "We specialize in manufacturing high-precision brass components for various industries, including automotive, aerospace, and more." },
    { icon: "💡", title: "Custom Brass Product Development", description: "Our team of experts works closely with clients to design and develop custom brass products that meet their specific requirements." },
    { icon: "🔩", title: "Brass Machining Services", description: "We offer precision machining services for brass products, including milling, turning, and grinding." },
    { icon: "📦", title: "Brass Product Export", description: "We export our high-quality brass products to clients across the globe, ensuring timely delivery and exceptional customer service." },
    { icon: "🔍", title: "Brass Quality Control", description: "Our rigorous quality control processes ensure that every brass product that leaves our facility meets the highest standards of quality and excellence." },
    { icon: "📈", title: "Brass Product Research and Development", description: "Our team of experts continuously works on researching and developing new brass products and technologies to stay ahead of the curve." }
  ],
  whyChooseUs: [
    { icon: "🏆", title: "Quality Excellence", description: "At Sumant Brass Industries, we are committed to delivering exceptional quality products that meet the highest standards of excellence." },
    { icon: "📊", title: "Competitive Pricing", description: "We offer competitive pricing for our brass products, ensuring that our clients receive the best value for their money." },
    { icon: "🕒", title: "Timely Delivery", description: "We understand the importance of timely delivery and ensure that our products reach our clients on time, every time." },
    { icon: "👥", title: "Experienced Team", description: "Our team of skilled professionals has years of experience in the brass manufacturing industry, ensuring that every product is crafted with precision and care." }
  ],
  testimonials: [
    { name: "Mahesh Chauhan", role: "Google Review", text: "This Place is currently right", rating: 5 }
  ],
  faq: { items: [{ question: "What types of brass products do you manufacture?", answer: "We manufacture a wide range of brass products, including components, fittings, and custom products. Please contact us to discuss your specific requirements." },
    { question: "Do you offer custom brass product development services?", answer: "Yes, our team of experts works closely with clients to design and develop custom brass products that meet their specific requirements." },
    { question: "What is your quality control process?", answer: "We have a rigorous quality control process in place to ensure that every brass product that leaves our facility meets the highest standards of quality and excellence." },
    { question: "Do you export your brass products?", answer: "Yes, we export our high-quality brass products to clients across the globe, ensuring timely delivery and exceptional customer service." },
    { question: "Can I visit your facility in Jamnagar?", answer: "Yes, we welcome clients to visit our facility in Jamnagar to see our manufacturing processes firsthand. Please contact us to schedule a visit." },
    { question: "What is your pricing policy?", answer: "We offer competitive pricing for our brass products, and our pricing policy is transparent and flexible. Please contact us to discuss your specific requirements and pricing." }] },
  ctaTitle: "Get a Quote Today!",
  ctaDescription: "Contact us to discuss your brass product requirements and get a quote from our team of experts.",
  ctaButtonText: "Request Quote",
  metaDescription: "Sumant Brass Industries: Leading manufacturer of high-quality brass products in Jamnagar, Gujarat.",
};

export const siteConfig = {
  layout: "playful",
  theme: "elegant",
  sections: ["gallery", "about", "services", "testimonials", "faq", "contact"],
  heroVariant: "fullscreen-image",
  navStyle: "minimal-top-nav",
  animationStyle: "parallax-sections",
  cardStyle: "rounded-2xl shadow-sm border",
  darkMode: false,
};
